default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: auto update by pre-commit hooks [skip changelog]"
  autofix_prs: true
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --config .prettierrc --write --ignore-unknown .
        language: node
        additional_dependencies:
          - prettier@3.6.2

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.19.1
    hooks:
      - id: markdownlint-cli2
        files: ^README\.md$
        types:
          - markdown
        args: ["--fix", "--config", ".markdownlint.yaml"]
