name: Lazy LaTeX Pipeline

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  package_and_publish:
    name: Package and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Package extension
        run: |
          pnpm package

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: lazy-latex-extension
          path: "*.vsix"

      - name: Publish release to GitHub
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        continue-on-error: true
        uses: softprops/action-gh-release@v2.4.2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          files: |
            *.vsix

      - name: Publish release to marketplace
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          if ${{ contains(github.ref_name, 'beta') }}; then
            pnpm vsce publish -p "${{ env.VSCE_PAT }}" --packagePath *.vsix --skip-duplicate --pre-release
          else
            pnpm vsce publish -p "${{ env.VSCE_PAT }}" --packagePath *.vsix --skip-duplicate
          fi
